# Generated by Django 4.0.2 on 2023-07-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CastoonnApp', '0004_profile_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_artist',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='passions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_artist',
            name='social_media_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
